baseURL = '/'
languageCode = 'en'
title = "Arul's Space"
PygmentsCodeFences = true
PygmentsStyle = "solarized-dark256"
pluralizelisttitles = "false"
paginate  = 18
disableHugoGeneratorInject = true

[params]
ava = "/img/profile-pic/img_5_1711286197424.jpg"

[module]
  [module.hugoVersion]
    extended = true
    min = "0.55.0"
theme = ["hugo-video", "red-rose"]
favicon = "/favicon.ico"


